services:

  todos-api:
    image: ursu/ant-todos-api:latest
    build:
      context: src
      dockerfile: ../dockerfiles/todos.Dockerfile
    ports:
      - "6001:8080"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"
      - "18889:18889"

  otel-collector:
    image: otel/opentelemetry-collector:0.24.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    ports:
      - "4317:4317"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
    volumes:
      - ./configs/otelcollector/otelcol-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - aspire-dashboard
