services:

  todos-api:
    image: ursu/ant-todos-api:latest
    build:
      context: src
      dockerfile: ../dockerfiles/todos.Dockerfile
    ports:
      - "6001:8080"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    env_file:
      - .env
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"
      - "18889:18889"
