global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "services"
    static_configs:
      - targets: [ "host.docker.internal:5001" ]
        labels:
          env: "localhost"
      - targets: [ "host.docker.internal:6001" ]
        labels:
          env: "docker"
