version: '3.7'

services: 

  todo-api:
    image: ursu/ant-todo-api:latest
    build:
      context: .
      dockerfile: todos-api.dockerfile
    ports:
      - 5001:80
    environment: 
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseOptions__TodoDatabase: "Server=mssqlserver;Database=Todo;User=sa;Password=Your_password123;"
      HangfireOptions__ConnectionString: "Server=mssqlserver;Database=Todo;User=sa;Password=Your_password123;"
      SwaggerOptions__ApplicationTitle: "Ant Todo Api Docker"
      LoggingOptions__ApplicationName: "Ant Todo Api Docker"
      LoggingOptions__ElasticSearchUrl: "http://elasticsearch:9200"
      ElasticApm__ServiceName: "Ant Todo Api Docker"
      ElasticApm__ServerUrls: "http://apm-server:8200"
    depends_on: 
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./Svc.Todos.Data/mssqlserver/mssql/data:/var/opt/mssql/data
      - ./Svc.Todos.Data/mssqlserver/sqlserver:/var/opt/mssqlserver

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.9.1
    ports:
      - "8200:8200"    
    depends_on:
      - elasticsearch
      - kibana
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    command: >
        apm-server -e
          -E apm-server.rum.enabled=true
          -E setup.kibana.host=kibana:5601
          -E setup.template.settings.index.number_of_replicas=0
          -E apm-server.kibana.enabled=true
          -E apm-server.kibana.host=kibana:5601
          -E output.elasticsearch.hosts=["elasticsearch:9200"]
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      cluster.name: "es-docker-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xms512m"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Svc.Todos.Data/elasticsearch/data:/usr/share/elasticsearch/data
