name: Build Todos Api

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/todos.yml"
      - "dockerfiles/todos.Dockerfile"
      - "src/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/todos.yml"
      - "dockerfiles/todos.Dockerfile"
      - "src/**"

jobs:

  dotnet-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  docker-build:
    runs-on: ubuntu-latest
    needs: dotnet-test
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -f dockerfiles/todos.Dockerfile src
